server:
  port: 8762
spring:
  application:
    name: spring-cloud-provider

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/